WITH HEAVY_REVIEWER AS (
    SELECT MEMBER_ID, RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) REVIEW_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT
    mp.MEMBER_NAME,
    rr.REVIEW_TEXT,
    DATE_FORMAT(rr.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW rr
INNER JOIN MEMBER_PROFILE mp USING (MEMBER_ID)
INNER JOIN HEAVY_REVIEWER hr USING (MEMBER_ID)
WHERE hr.REVIEW_RANK = 1
ORDER BY rr.REVIEW_DATE, rr.REVIEW_TEXT;