SELECT 
    ri.REST_ID,
    ri.REST_NAME,
    ri.FOOD_TYPE,
    ri.FAVORITES,
    ri.ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE), 2) SCORE
FROM REST_INFO ri
INNER JOIN REST_REVIEW rr USING (REST_ID)
WHERE ADDRESS like '서울%'
GROUP BY ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES
ORDER BY SCORE DESC, ri.FAVORITES DESC;