WITH RANKED_PRODUCT AS (
    SELECT 
        CATEGORY, 
        PRICE, 
        PRODUCT_NAME,
        RANK() OVER (
                PARTITION BY CATEGORY
                ORDER BY PRICE DESC
        ) RANKING
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM RANKED_PRODUCT
WHERE RANKING = 1
ORDER BY MAX_PRICE DESC;