SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT fp
INNER JOIN FOOD_ORDER fo ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE fo.PRODUCE_DATE >= '2022-05-01' AND fo.PRODUCE_DATE < '2022-06-01'
GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, fp.PRODUCT_ID;