WITH USER_JOINED_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

SELECT
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT os.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID) / (SELECT COUNT(*) FROM USER_JOINED_2021), 1) PURCHASED_RATIO
FROM ONLINE_SALE os
WHERE USER_ID IN (SELECT USER_ID FROM USER_JOINED_2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;