SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * bs.SALES) TOTAL_SALES
FROM
    BOOK b
INNER JOIN
    AUTHOR a USING (AUTHOR_ID)
INNER JOIN
    BOOK_SALES bs USING (BOOK_ID)
WHERE
    bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC;