WITH BOOK_SALES_IN_JANUARY AS (
    SELECT
        BOOK_ID,
        SUM(SALES) SALES
    FROM
        BOOK_SALES
    WHERE
        SALES_DATE BETWEEN
        '2022-01-01'
        AND
        '2022-01-31'
    GROUP BY
        BOOK_ID
)

SELECT
    CATEGORY,
    SUM(bj.SALES) TOTAL_SALES
FROM
    BOOK
INNER JOIN
    BOOK_SALES_IN_JANUARY bj USING (BOOK_ID)
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY;