WITH CAR_RENTAL_OVER_5_BETWEEN_AUGUST_AND_OCTOBER AS (
    SELECT
        CAR_ID,
        COUNT(CAR_ID)
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY
        CAR_ID
    HAVING
        COUNT(CAR_ID) >= 5
)

SELECT
    MONTH(START_DATE) MONTH,
    CAR_ID,
    COUNT(*) RECORDS
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN (
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_OVER_5_BETWEEN_AUGUST_AND_OCTOBER
    )
    AND
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    MONTH(START_DATE), CAR_ID
ORDER BY
    MONTH(START_DATE), CAR_ID DESC