WITH CHECK_AVAILABLE AS (
    SELECT
        CAR_ID,
        '대여중' AVAILABILTY
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
    GROUP BY
        CAR_ID
)

SELECT
    CAR_ID,
    IFNULL(ca.AVAILABILTY, '대여 가능')
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
LEFT JOIN
    CHECK_AVAILABLE ca USING (CAR_ID)
GROUP BY
    CAR_ID
ORDER BY
    CAR_ID DESC