-- INNER JOIN
SELECT ai.ANIMAL_ID, ai.NAME
FROM ANIMAL_INS ai
INNER JOIN ANIMAL_OUTS ao ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.DATETIME > ao.DATETIME
ORDER BY ai.DATETIME;

-- SUBQUERY
SELECT ai.ANIMAL_ID, ai.NAME
FROM ANIMAL_INS ai
WHERE EXISTS (
    SELECT 1
    FROM ANIMAL_OUTS ao
    WHERE ai.ANIMAL_ID = ao.ANIMAL_ID AND ai.DATETIME > ao.DATETIME
)
ORDER BY ai.DATETIME;