-- INNER JOIN
SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS ai
INNER JOIN ANIMAL_OUTS ao ON ao.ANIMAL_ID = ai.ANIMAL_ID
WHERE ai.SEX_UPON_INTAKE LIKE "Intact %" AND (ao.SEX_UPON_OUTCOME LIKE "Spayed %" OR ao.SEX_UPON_OUTCOME LIKE "Neutered %")

-- SUBQUERY
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS ai
WHERE SEX_UPON_INTAKE LIKE "Intact %"
    AND EXISTS (
        SELECT 1
        FROM ANIMAL_OUTS ao
        WHERE ai.ANIMAL_ID = ao.ANIMAL_ID 
          AND (ao.SEX_UPON_OUTCOME LIKE "Spayed %" OR ao.SEX_UPON_OUTCOME LIKE "Neutered %")
    )