WITH RECURSIVE TIMES AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIMES WHERE HOUR < 23
)
SELECT t.HOUR, COUNT(ao.DATETIME) count
FROM TIMES t
LEFT JOIN ANIMAL_OUTS ao on t.HOUR = HOUR(ao.DATETIME)
GROUP BY t.HOUR
ORDER BY t.HOUR;