WITH HEAVY_USERS AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) > 1
)
SELECT ID, NAME, PLACES.HOST_ID
FROM PLACES
JOIN HEAVY_USERS ON HEAVY_USERS.HOST_ID = PLACES.HOST_ID
ORDER BY ID;